### ISSUE TITLE
Exception "Empty response received" when calling CreateQuery

### ISSUE THREAD

**Issue by ZhangYiQiu** [justdmitry/TonLib.NET#1]
![image](https://user-images.githubusercontent.com/22910338/233766230-8a69663e-5ef6-481c-9598-25e614ad66c7.png)

**Comment by justdmitry** [comment]
Library has sent the request, but received empty text as response.

Usually this happens when LiteServer you connected to has failed to answer. So you just need to reconnect (call `InitIfNeeded()` again) and retry `CreateQuery` call.

Sometimes tonlib can fail to parse your request - this has happened to me when I tried to send "really strange or wrong" requests (garbage instead of base64 bytes etc).

So first this here is to make sure you enabled (didn't disable) logging and check "Sending" and "Received" log entries, like this:
![cmd_2023-04-24_11-20-50](https://user-images.githubusercontent.com/3540597/233940329-b4a714c7-de8c-4acb-9190-1f8fc72db769.png)

Usually this logs can give you some knowledge what exactly happened.
