### ISSUE TITLE
Implementation wallet functionality

### ISSUE THREAD

**Issue by tanderbold** [justdmitry/TonLib.NET#2]
First of all, thank you for creating a library for C#.
It would be great to be able to work with private keys without importing them into the storage.
Like here
https://github.com/xssnick/tonutils-go/blob/master/ton/wallet/wallet.go#L430

**Comment by justdmitry** [comment]
What of https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/tonlib_api.tl you want to use that doesn't require imported keys? It seems everything wants your keys to be imported...

**Comment by tanderbold** [comment]
Hi there,
I think that is possible with wallet contracts (https://docs.ton.org/participate/wallets/contracts) example of implementation is here https://github.com/xssnick/tonutils-go/tree/master#Wallet
1. Generate a seed without client calls with words from here (https://github.com/xssnick/tonutils-go/blob/master/ton/wallet/seed.go)
2. Generate a private key from the seed
3. Deploy a wallet contract on first time use

Wallets are deployed on blockchain and later we can operate with the private key without importing (like in this example https://github.com/xssnick/tonutils-go/blob/master/example/wallet/main.go)

**Comment by justdmitry** [comment]
The big difference between tonlib.net and tonutils-go is that tonlib.net uses native c++ ton library (tonlib) to interact with blockchain servers, while tonutils-go communicates with servers directly (using sockets). So when using tonlib - only calls implemented by tonlib are possible. And all tonlib wallet interaction methods require imported key, so implementing crypto-operations in c# is useless because you can't use them with tonlib.

Of course I may be wrong and tonlib may have some methods that can interact with blockchain without importing keys, but docs are not too detailed and I need more info about such methods if they exist.

**Comment by tanderbold** [comment]
Ok, thank you for your reply and have a nice day
