### ISSUE TITLE
How to import wallet with mnemonic without adding keypair into folder?

### ISSUE THREAD

**Issue by mightatnight** [justdmitry/TonLib.NET#5]

**Comment by justdmitry** [comment]
You may use `KeyStoreTypeInMemory`. Use it in [TonOptions.KeystoreType](https://github.com/justdmitry/TonLib.NET/blob/master/TonLibDotNet.Demo/Program.cs#L32) instead of `KeyStoreTypeDirectory`.

After this change, you'll be required to re-add all used wallets on program startup, so you will still need to store mnemonics somewhere around. And also tonlib will need to resync with liteserver(s) from scratch on every startup (because it stores something in this storage too), which takes time (about 30-40sec IIRC).
